"""schema_v1

Revision ID: 838e62830e37
Revises: 0001
Create Date: 2026-05-12 09:05:35.296990+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '838e62830e37'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), server_default=sa.text("'employee'"), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('employee','lead','admin')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_user_id')
    )
    op.create_index('idx_users_department_id', 'users', ['department_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_conversations_user_updated', 'ai_conversations', ['user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'new'"), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('assignee_id', sa.BigInteger(), nullable=True),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('dept_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('dept_message_id', sa.Integer(), nullable=True),
    sa.Column('arch_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_2d_sent', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('reminder_1d_sent', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('reminder_2h_sent', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('is_message_purged', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.CheckConstraint("priority IN ('low','medium','high','urgent')", name='ck_tasks_priority'),
    sa.CheckConstraint("status IN ('new','in_progress','done','cancelled')", name='ck_tasks_status'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_assignee', 'tasks', ['assignee_id'], unique=False)
    op.create_index('idx_tasks_deadline', 'tasks', ['deadline'], unique=False, postgresql_where=sa.text("status IN ('new','in_progress')"))
    op.create_index('idx_tasks_dept_status', 'tasks', ['department_id', 'status'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('task_files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_file_id', sa.String(length=255), nullable=False),
    sa.Column('tg_file_unique_id', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_files_task_id', 'task_files', ['task_id'], unique=False)
    op.create_table('task_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('created','accepted','completed','cancelled','commented','reassigned','deadline_changed')", name='ck_task_history_event_type'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_history_task', 'task_history', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_history_task', table_name='task_history')
    op.drop_table('task_history')
    op.drop_index('idx_task_files_task_id', table_name='task_files')
    op.drop_table('task_files')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_dept_status', table_name='tasks')
    op.drop_index('idx_tasks_deadline', table_name='tasks', postgresql_where=sa.text("status IN ('new','in_progress')"))
    op.drop_index('idx_tasks_assignee', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_ai_conversations_user_updated', table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index('idx_users_department_id', table_name='users')
    op.drop_table('users')
    op.drop_table('departments')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
